### ISSUE TITLE
contributing guidelines suggestion

### ISSUE THREAD

**Issue by waalge** [sblauth/cashocs#2]
Contributing guidelines state _Use the same coding conventions as established in the project._ 
Might it be helpful to unpack this?
Or more explicitly adding flake8. 

(I'm incredibly petty and get put off working with anything that isn't blacked.)

**Comment by sblauth** [comment]
Thanks for this comment, and I totally get your point. 
I've now changed the coding style to black and updated the contributing guidelines accordingly. 

This should close the issue, if not, please feel free to reopen it.
