### ISSUE TITLE
Visualization error using jupyter notebook

### ISSUE THREAD

**Issue by JamJamkid** [sblauth/cashocs#508]
Hi everyone,

I have encountered a problem while solving a Poisson shape optimization problem. I ran the code downloaded from Cashocs but I got the following error:

![1729242303519](https://github.com/user-attachments/assets/3016707f-a752-472e-a1ef-f86857fdaaa8)

![1729242426330](https://github.com/user-attachments/assets/77b218a6-3483-4407-93b4-ee91c48bc610)

**Comment by sblauth** [comment]
Thanks for opening an issue regarding your problem. 
Based on your description, it seems to me like you are solving the following problem: https://cashocs.readthedocs.io/en/stable/user/demos/shape_optimization/demo_shape_poisson/

From the output, everything first works as expected - the optimization is successful. Afterwards there is some issue - I guess related to plotting the function, but I am not sure. 

To find a solution to your problem, can you please provide the following:

- Which version of cashocs are you using 
  you can check this with the lines
  ```
  import cashocs
  print(cashocs.__version__)
  ```
- How you have installed cashocs
- Where you are running the script from (which IDE, jupyter notebook, bash, ...)
- The complete code in form of a minimal working example (if you are using one of cashocs' demos, then this will be minimal enough)

**Comment by JamJamkid** [comment]
Thank you very much for your reply. I ran the exact same code from my jupyter notebook. I installed it in a virtual environment via pip3. Here is my version of Cashocs.
![1729251876247](https://github.com/user-attachments/assets/52372a6c-6258-4989-8138-68d8d6312a7e)

**Comment by JamJamkid** [comment]
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
binutils_impl_linux-64    2.40                 h5293946_0    defaults
binutils_linux-64         2.40                 hb3c18ed_9    conda-forge
bzip2                     1.0.8                h5eee18b_6    defaults
c-ares                    1.32.3               h4bc722e_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cashocs                   2.2.0                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
cmake                     3.28.3               hcfe8598_0    conda-forge
comm                      0.2.1           py311h06a4308_0    defaults
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.6.7           py311h6a678d5_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
eigen                     3.4.0                h00ab1b0_0    conda-forge
executing                 0.8.3              pyhd3eb1b0_0    defaults
expat                     2.6.3                h6a678d5_0    defaults
fenics                    2019.1.0                 pypi_0    pypi
fenics-dijitso            2019.1.0          pyhd8ed1ab_39    conda-forge
fenics-dolfin             2019.1.0        py311hbd72059_43    conda-forge
fenics-ffc                2019.1.0.post0           pypi_0    pypi
fenics-fiat               2019.1.0          pyhd8ed1ab_39    conda-forge
fenics-libdolfin          2019.1.0            hc532c93_43    conda-forge
fenics-ufl                2019.1.0        py311h38be061_38    conda-forge
fftw                      3.3.10          mpi_mpich_hbcf76dd_10    conda-forge
fonttools                 4.54.1                   pypi_0    pypi
gcc_impl_linux-64         12.4.0               hb2e57f8_1    conda-forge
gcc_linux-64              12.4.0               h6b7512a_4    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmsh                      4.13.1                   pypi_0    pypi
gxx_impl_linux-64         12.4.0               h613a52c_1    conda-forge
gxx_linux-64              12.4.0               h8489865_4    conda-forge
h5py                      3.10.0                   pypi_0    pypi
hdf5                      1.14.3          mpi_mpich_h0f54ddc_5    conda-forge
hypre                     2.28.0          mpi_mpich_h716cb5e_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
ipykernel                 6.29.5          py311h06a4308_0    defaults
ipython                   8.27.0          py311h06a4308_0    defaults
jedi                      0.19.1          py311h06a4308_0    defaults
jupyter_client            8.6.0           py311h06a4308_0    defaults
jupyter_core              5.7.2           py311h06a4308_0    defaults
kernel-headers_linux-64   3.10.0              he073ed8_17    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7                    pypi_0    pypi
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.40                 h12ee557_0    defaults
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libboost                  1.84.0               hba137d9_3    conda-forge
libboost-headers          1.86.0               ha770c72_2    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.4                h6a678d5_1    defaults
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     12.4.0             ha4f9413_101    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
libmpdec                  4.0.0                h5eee18b_0    defaults
libnghttp2                1.58.0               h47da74e_1    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libptscotch               7.0.4                h2376d02_5    conda-forge
libsanitizer              12.4.0               h46f95d5_1    conda-forge
libscotch                 7.0.4                h3055ed5_5    conda-forge
libsodium                 1.0.18               h7b6447c_0    defaults
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-64  12.4.0             ha4f9413_101    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libuuid                   1.41.5               h5eee18b_0    defaults
libuv                     1.49.1               hb9d3cd8_0    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
markdown-it-py            3.0.0                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.6           py311h06a4308_0    defaults
mdurl                     0.1.2                    pypi_0    pypi
meshio                    5.3.5                    pypi_0    pypi
metis                     5.1.0             hd0bcaf9_1007    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpi                       1.0.1                     mpich    conda-forge
mpi4py                    3.1.6           py311h0b14fea_1    conda-forge
mpich                     4.2.3              h670b19f_100    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
mumps-include             5.6.2                ha770c72_4    conda-forge
mumps-mpi                 5.6.2                h416f8d4_4    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.6.0           py311h06a4308_0    defaults
netcdf4                   1.7.1.post2              pypi_0    pypi
numpy                     2.1.2                    pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1            py311h06a4308_0    defaults
parmetis                  4.0.3             h583469f_1006    conda-forge
parso                     0.8.3              pyhd3eb1b0_0    defaults
petsc                     3.20.6          real_h247c841_100    conda-forge
petsc4py                  3.20.5          real_h92a2bec_100    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pillow                    11.0.0                   pypi_0    pypi
pip                       24.2            py311h06a4308_0    defaults
pkg-config                0.29.2            h4bc722e_1009    conda-forge
pkgconfig                 1.5.5              pyhd8ed1ab_4    conda-forge
platformdirs              3.10.0          py311h06a4308_0    defaults
prompt-toolkit            3.0.43          py311h06a4308_0    defaults
prompt_toolkit            3.0.43               hd3eb1b0_0    defaults
psutil                    5.9.0           py311h5eee18b_0    defaults
ptscotch                  7.0.4                h23d43cc_5    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pybind11                  2.12.0          py311h9547e67_0    conda-forge
pybind11-global           2.12.0          py311h9547e67_0    conda-forge
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
python                    3.11.10              he870216_0    defaults
python-dateutil           2.9.0post0      py311h06a4308_2    defaults
python_abi                3.11                    2_cp311    conda-forge
pyzmq                     25.1.2          py311h6a678d5_0    defaults
readline                  8.2                  h5eee18b_0    defaults
rhash                     1.4.5                hb9d3cd8_0    conda-forge
rich                      13.9.2                   pypi_0    pypi
scalapack                 2.2.0                h417d24c_2    conda-forge
scipy                     1.14.1                   pypi_0    pypi
scotch                    7.0.4                h23d43cc_5    conda-forge
setuptools                75.1.0          py311h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
slepc                     3.20.2          real_h31e5b42_100    conda-forge
slepc4py                  3.20.2          real_h8c3e9f8_100    conda-forge
sqlite                    3.45.3               h5eee18b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
suitesparse               5.10.1               h5a4f163_3    conda-forge
superlu                   5.2.2                h00795ac_0    conda-forge
superlu_dist              8.2.1                he925d4f_1    conda-forge
sympy                     1.13.3             pyh04b8f61_4    conda-forge
sysroot_linux-64          2.17                h4a8ded7_17    conda-forge
tbb                       2021.13.0            h84d6215_0    conda-forge
tk                        8.6.14               h39e8969_0    defaults
tornado                   6.4.1           py311h5eee18b_0    defaults
traitlets                 5.14.3          py311h06a4308_0    defaults
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0          py311h06a4308_0    defaults
tzdata                    2024b                h04d1e81_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.44.0          py311h06a4308_0    defaults
xz                        5.4.6                h5eee18b_1    defaults
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.5                h6a678d5_0    defaults
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by JamJamkid** [comment]
![1729252393987](https://github.com/user-attachments/assets/85a48a82-bfb6-4d72-818e-4b318eda91bd)
![1729252452357](https://github.com/user-attachments/assets/24f13b72-a156-42f0-8beb-f026abcf5f4d)
![1729252488063](https://github.com/user-attachments/assets/e7ba7b76-53b2-4392-b297-74e0f5f9c1a8)
![1729252521841](https://github.com/user-attachments/assets/2dea07dc-ac9f-4acc-a48b-2f26b1bdc7cc)

**Comment by sblauth** [comment]
I am not really familiar with Jupyter Notebook. I guess that the problematic code is the following:

```
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

ax_mesh = plt.subplot(1, 2, 1)
fig_mesh = plot(mesh)
plt.title("Discretization of the optimized geometry")

ax_u = plt.subplot(1, 2, 2)
ax_u.set_xlim(ax_mesh.get_xlim())
ax_u.set_ylim(ax_mesh.get_ylim())
fig_u = plot(u)
plt.colorbar(fig_u, fraction=0.046, pad=0.04)
plt.title("State variable u")

plt.tight_layout()
# plt.savefig('./img_shape_poisson.png', dpi=150, bbox_inches='tight')
```

You could, of course, try commenting this and not get the plots - this would at least get rid of the error message. 
It could be worth to also try the following: https://stackoverflow.com/questions/19410042/how-to-make-ipython-notebook-matplotlib-plot-inline

But this is not an issue with cashocs, it's one that concerns matplotlib (and I guess using it with a jupyter notebook) - so I am sorry that I cannot help any further at the moment.

**Comment by JamJamkid** [comment]
Thank you very much for your reply. I can comment this but how do I view my results?

**Comment by sblauth** [comment]
The best approach for doing so does not involve matplotlib anyway. 
You can specify the following parameters in the configuration file

```
...

[Output]
save_state = True
save_adjoint = True
save_gradient = True
...
```

which will automatically store the state variables, adjoint variables, and gradient over the course of the optimization in the XDMF file format, which can be viewed with Paraview. They are saved in the `result_dir` which is specified in 

```
...
[Output]
result_dir = ./
...
```

where the default path is `./`, so the current directory, from which the script is run.

**Comment by JamJamkid** [comment]
Thank you very much for your help. I solved this issue very well using the method you proposed. Finally, I would like to ask whether Cashocs can calculate the following unconstrained shape optimization problem?
![1729255290878](https://github.com/user-attachments/assets/c2dd3f52-95aa-4dde-a8fd-260ea334adc6)

**Comment by sblauth** [comment]
Yes, you can do so with cashocs. You can just specify any PDE constraint - if the cost functional does not depend on the solution of this, it works fine. So you could define your cost functional as follows (and keep the rest of the demo identical)

```
x = SpatialCoordinate(mesh)
J = cashocs.IntegralFunctional(((x[0] - 0.5)**2 + (x[1] - 0.5)**2 - 0.5) * dx)
```

which will solve the problem. Just make sure that the initial guess is not too far off as this could result in instabilities.

PS: When I solve unconstrained problems with cashocs, I usually use a Poisson problem as PDE constraint with homogeneous Dirichlet boundary conditions and zero right-hand-side. Then, the solution of the PDE constraint is 0, too, and this will result in the least numerical effort used.

**Comment by JamJamkid** [comment]
Thank you very much for your help, I will try to do it.  Best wishes to you.

**Comment by JamJamkid** [comment]
Dear Sebastian Blauth
I am running the demo of Topology Optimization with a Poisson Equation,  and I would like to ask how to save the optimal Psi as a .xdmf file?
![1731376189804](https://github.com/user-attachments/assets/5e886bc8-cfd5-4309-b5f0-9026ab1facb2)

**Comment by sblauth** [comment]
As you are asking for the optimal psi (which is the levelset function) this can be done by using the configuration parameters

```
[Output]
save_state = True
```

which will automatically save the state and "control" variable as xdmf file. For topology optimization, the levelset function is the control. So you can directly open this with, e.g., paraview.

To recreate a picture as the one above, you then need to apply a threshold filter to the levelset function. 

I hope this solves your issue. Feel free to reopen this issue if you encounter any problems.
